
server.port: 8002

spring.application.name: swagger service

eureka:
  instance:
    prefer-ip-address: true
    status-page-url-path: /swagger-ui.html
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.40.100:8000/eureka/,http://192.168.40.101:8000/eureka/,http://192.168.40.102:8000/eureka/