eureka:
  server:
    renewal-percent-threshold: 0.49
  instance:
    hostname: localhost
  client:
    eureka-server-port: 8100
#    enabled: false
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


spring:
  application:
    name: enreka-server
server:
  port: 8000